ALTER TABLE [dbo].[tNode] ADD CONSTRAINT [PK_tNode] PRIMARY KEY CLUSTERED ([Id])
	WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO
CREATE CLUSTERED INDEX [IX_tNodeTag_NodeId_Typ] ON [dbo].[tNodeTag] ([NodeId] ASC,[Typ] ASC)
	WITH (STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO