ALTER TABLE [dbo].[tRelation] ADD CONSTRAINT [PK_tRelation] PRIMARY KEY CLUSTERED ([Id], [Role])
	WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO
ALTER TABLE [dbo].[tRelationCreation] ADD CONSTRAINT [PK_tRelationCreation] PRIMARY KEY CLUSTERED ([RelationId], [Sort])
	WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO
CREATE CLUSTERED INDEX [IX_tRelationTag_RelationId_Typ] ON [dbo].[tRelationTag] ([RelationId], [Typ])
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO