ALTER TABLE [dbo].[tWay] ADD CONSTRAINT [PK_tWay] PRIMARY KEY CLUSTERED ([Id])
	WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO
ALTER TABLE [tWayCreation] ADD CONSTRAINT [PK_tWayCreation] PRIMARY KEY CLUSTERED ([WayId], [NodeId], [Sort])
	WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO
CREATE CLUSTERED INDEX [IX_tWayTag_WayId_Typ] ON [dbo].[tWayTag] ([WayId], [Typ])
	WITH (STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO